
# This is a basic workflow to help you get started with Actions
name: Build and Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - uoft
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          submodules: true

      - name: Extract branch name
        shell: bash
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch

      - name: Install and Build ðŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        env:
          REPO_NAME: ${{ github.event.repository.full_name }}
          BRANCH_NAME: ${{ env.branch_name }}
        run: |
          export DEPLOY_BRANCH="gh-pages-$BRANCH_NAME-no-jsdelivr"
          echo "deploy_branch=${DEPLOY_BRANCH}"  >> $GITHUB_ENV
          CDN_URL="."
          VERSION_NUMBER="v$(grep -oP '"version": "\K[^"]+' package.json | head -n1)"
          npm install
          npm audit fix
          echo "DEPLOY_BRANCH=$DEPLOY_BRANCH, VERSION_NUMBER=$VERSION_NUMBER, CDN_URL=$CDN_URL"
          CI=false PUBLIC_URL=$CDN_URL REACT_APP_BUILD_INFO=$VERSION_NUMBER npm run build

      - name: Deploy ðŸš€
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ env.deploy_branch }} # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch